spring:
  profiles:
    active: dev
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/link_shortener
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: link_shortener
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 3000
      password: root
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: messages

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation=DEBUG:

rabbit:
  topic-exchange-name: link-shortener
  queue-name: SEND_EMAIL


open-api:
  title: link-shortener
  description: This API belongs to UKKU CORP.
  version: 1.0.0

security:
  jwt:
    public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8DtKOpJRcQ99U6TreSo9gIdn9Vw/z8N9RlEwTvl3jkn6taVoQBeuGD+pOrKoR6BA4DUBhZFP6hCH25mItF7/lgKqO8Gj/WYSFu3g9HYtR2gF0JbdLdNhJ9p+7gfXphgjh1Y1LWDoygnlQvsepZSoBNlG+0juHYRSPJ7VEjICEp580Q9Sb9m5NCFSJtonk3n7ReXHFrpioQTSJyzUUwlBJJmsG8WVVNxUzqO8K6E0sDKaLJJMlnhDit0VeMn4+yOPVI2lOvWd9OSC7O6Ni/fivmi6edWGmcGNWcCDRAbyRnZhWgM02HiYNRyW+wporokVNKvvcS2VAZZaOd4TFCC1dwIDAQAB
    private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDwO0o6klFxD31TpOt5Kj2Ah2f1XD/Pw31GUTBO+XeOSfq1pWhAF64YP6k6sqhHoEDgNQGFkU/qEIfbmYi0Xv+WAqo7waP9ZhIW7eD0di1HaAXQlt0t02En2n7uB9emGCOHVjUtYOjKCeVC+x6llKgE2Ub7SO4dhFI8ntUSMgISnnzRD1Jv2bk0IVIm2ieTeftF5ccWumKhBNInLNRTCUEkmawbxZVU3FTOo7wroTSwMposkkyWeEOK3RV4yfj7I49UjaU69Z305ILs7o2L9+K+aLp51YaZwY1ZwINEBvJGdmFaAzTYeJg1HJb7CmiuiRU0q+9xLZUBllo53hMUILV3AgMBAAECggEAFqIXY75OUv8ZGSzUDJXYtofLWRgIYQwzfNEAYqhpRawdpUiAsm0ot1skGAYmCZ2FDzqfOpTOuSg2jI+CDDBZFyqIHFopl6GquaNOyulpaa1Ywua7zun34NfalpWBkUH78u/B0dUsCYD2KyHaqNIBJHfOErWzzW8eilySiYTRoixCqkzkL7dSjtG5h/eqqxFpYizt0n7gImoqSl/Tc+f3B80/WvtELQCdUvnqk3Hma3iKmFsyszMfKWxU05haMwjTOXWk/v1UB3jMfE5e9KPwAUWLaIFxkILpnTsbbKvHNgdZrDfaru+981xsCiIQl+vQVQuzgYXpJkJjEDqxIEfOqQKBgQD+tWE0XDAEXsPECLJjHMIufnamAlISOKrk8BVann6eIncpk6NsNMqxGEE5fDDLgdfMQCqy6SOeI2AbJs9dV+M1G8dvM44oRjYpltmm+PH7/tfVDRhHI0CD4LiefqK7Q2Fygd5QKz7OY1seiidZRkzPxA7q+8aXWF32WwNSyKUSeQKBgQDxcx5k3eNIvTk4jiyiKnfZPAJQuKrKigvo1uXP/xIiKF70CsWChkICwfaQpIPh4QLXq8abAhAzMs/+KI1YruFQPRd0lnjaC+8CSOx8ebyCd3FblgpXaI2tZyw6RcQ+O/aogM5D0TeDP6x5hEP8exqdgjD9MZNotLQTPr4rfjaLbwKBgCs5uN9b7cIwGuT/3NY5ITMmvxf5ONhiyY3EuLsCPtazXqmtpoRMiUF4rkkFLHq89FRzZ0upiSPjOQIimfprWeG/bx8ODsgC8loogZN2mAp9+z7q0/3um5pF3s73CsLg8n6uT34neKcp8WLDa14ZMhvoV+fFBrTUiE2wsGWyK2FxAoGBAN9aX6ZtQEBckt9HXfCRmpaBFZ84hP2hoAy/Jo43Zb3lXJkikb0Bl3TXmtAI79r2/FsoEyv3R6ck/RUezEpaVCGWseju/VKvsWSKswEe2AxUk69mZ6CeHllnVJl/Sl9Ltwv/Q0+m7VRjhZhPi1i3RFKqSckeoD8+0knvQ5oWQjzPAoGANg/REBM0bZDO53Pf2VNyaB4f4IEetRKyHX5V1yuSgjC8pHc8zijHcaZPrKCM4ULHW3H8UW52SrUeFKamucuemrwn13Jy09knn3QBdUWhmNOPsDdCy7DOTFBbyiKwWwuW6+F+eiqeOGrZ13O73VVCNZJgaoVMZ4H+iziz3qSE6Mo=
    validity-time: 1800000
  allowed-urls:
    - /v3/api-docs/**
    - /swagger-ui/**
    - /api/v1/auth/login
    - /api/v1/auth/register
    - /api/v1/auth/verify
    - /api/v1/links/redirect/**
    - /api/v1/test/all/**