version: '3'
services:
  link-shortener-db:
    image: mysql:8.2.0
    container_name: link-shortener-db
    environment:
      MYSQL_DATABASE: 'link_shortener'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3306:3306"
    volumes:
      - link-shortener-db:/var/lib/mysql
  link-shortener-redis:
    image: bitnami/redis:6.2.14
    container_name: link-shortener-redis
    restart: always
    environment:
      - REDIS_PASSWORD=root
    ports:
      - '6379:6379'
  link-shortener-rabbit:
    image: rabbitmq:management
    container_name: link-shortener-rabbit
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  link-shortener-db: